#include "Resources.h"
#include "SDL_macros.h"

vector<Resources::FontInfo> Resources::fonts_{
	//
	{Basic, ARIAL12, "../AnimalCooking/resources/fonts/ARIAL.ttf", 12 },
	{Basic, ARIAL50, "../AnimalCooking/resources/fonts/ARIAL.ttf", 50 },
	{Basic, ARIAL40, "../AnimalCooking/resources/fonts/ARIAL.ttf", 40 },
	{Basic, QuarkCheese100, "../AnimalCooking/resources/fonts/QuarkCheese.otf", 100 },
	{Basic, QuarkCheese200, "../AnimalCooking/resources/fonts/QuarkCheese.otf", 200 },
	{Basic, QuarkCheese70, "../AnimalCooking/resources/fonts/QuarkCheese.otf", 70 },
	{Basic, QuarkCheese62, "../AnimalCooking/resources/fonts/QuarkCheese.otf", 62 },
	{Basic, QuarkCheese50, "../AnimalCooking/resources/fonts/QuarkCheese.otf", 50 }

};




vector<Resources::ImageInfo> Resources::images_{
	//	
	//----->Menu<--------------
	{Basic, MainMenuBackground,"../AnimalCooking/resources/images/Menu/mainmenu.png"},
	{Basic, MainMenuRuedecilla,"../AnimalCooking/resources/images/Menu/Boton/boton.png"},
	{Basic, MainMenuRuedecillaShadow,"../AnimalCooking/resources/images/Menu/Boton/sombraboton.png"},
	{Basic, MainMenuArrow,"../AnimalCooking/resources/images/Menu/Boton/flecha.png"},
	{Basic, MainMenuArrowR,"../AnimalCooking/resources/images/Menu/Boton/flechar.png"},
	{Basic, MainMenuPlayButton,"../AnimalCooking/resources/images/Menu/Boton/playButton.png"},
	{Basic, MainMenuConfigButton,"../AnimalCooking/resources/images/Menu/Boton/configButton.png"},
	{Basic, MainMenuTutorialButton,"../AnimalCooking/resources/images/Menu/Boton/howToPlay.png"},
	{Basic, MainMenuExitButton,"../AnimalCooking/resources/images/Menu/Boton/exitButton.png"},
	{Basic, MainMenuCreditsButton,"../AnimalCooking/resources/images/Menu/Boton/creditsButton.png"},

	{Basic, TutorialImageBackground,"../AnimalCooking/resources/images/Tutorial/marco.png"},
	{Basic, TutorialImage0,"../AnimalCooking/resources/images/Tutorial/tuto1.png"},
	{Basic, TutorialImage1,"../AnimalCooking/resources/images/Tutorial/tuto2.png"},
	{Basic, TutorialImage2,"../AnimalCooking/resources/images/Tutorial/tuto3.png"},
	{Basic, TutorialImage3,"../AnimalCooking/resources/images/Tutorial/tuto4.png"},
	{Basic, TutorialImage4,"../AnimalCooking/resources/images/Tutorial/tuto5.png"},
	{Basic, TutorialImage5,"../AnimalCooking/resources/images/Tutorial/tuto6.png"},
	{Basic, TutorialBarra,"../AnimalCooking/resources/images/Tutorial/tutorial.png"},

	//----->InGame<--------------
	{Basic, LevelTimerBackground,"../AnimalCooking/resources/images/barraSinCargar.png"},
	{Basic, LevelTimerForeground,"../AnimalCooking/resources/images/cargaBarra.png"},
	{Basic, UtensilTimerBackground,"../AnimalCooking/resources/images/gotaSinCarga.png"},
	{Basic, UtensilTimerForeground,"../AnimalCooking/resources/images/gotaCarga.png"},
	{Basic, ScoreBackground,"../AnimalCooking/resources/images/ScoreBackground.png"},
	{Basic, PingUtensil,"../AnimalCooking/resources/images/ping.png"},

	//----->EndState<---------
	{Basic, BackgroundEndState,"../AnimalCooking/resources/images/EndState/background.png"},
	{Basic, BarBackgroundEndState,"../AnimalCooking/resources/images/EndState/barraSin.png"},
	{Basic, BarEndState,"../AnimalCooking/resources/images/EndState/barraCon.png"},
	{Basic, Star,"../AnimalCooking/resources/images/EndState/star.png"},
	{Basic, YellowStar,"../AnimalCooking/resources/images/EndState/YellowStar.png"},
	{Basic, LimitSign,"../AnimalCooking/resources/images/EndState/Indicador.png"},

	//MapState
	{ Basic, NameAsker, "../AnimalCooking/resources/images/provisional/NameAskerBG.png" },
	{ Basic, MapStateBackground, "../AnimalCooking/resources/images/Mapstate/mapState.png" },
	{ Basic, MapState2Background, "../AnimalCooking/resources/images/Mapstate/mapState2.png" },
	{ Basic, MapState3Background, "../AnimalCooking/resources/images/Mapstate/mapState3.png" },
	{ Basic, MapState4Background, "../AnimalCooking/resources/images/Mapstate/mapState4.png" },
	{ Basic, MapStateStarBox, "../AnimalCooking/resources/images/Mapstate/panelMapInfo.png" },
	{ Basic, MapStateInfoBox, "../AnimalCooking/resources/images/Mapstate/panelMapInfo2.png" },


	//Botones del mando
	{ Basic, GPad_a, "../AnimalCooking/resources/images/Menu/ButtonUIMando/aButton.png" },
	{ Basic, GPad_b,"../AnimalCooking/resources/images/Menu/ButtonUIMando/bButton.png" },
	{ Basic, GPad_x, "../AnimalCooking/resources/images/Menu/ButtonUIMando/xButton.png" },
	{ Basic, GPad_y, "../AnimalCooking/resources/images/Menu/ButtonUIMando/yButton.png" },
	{ Basic, GPad_up, "../AnimalCooking/resources/images/Menu/ButtonUIMando/upButton.png" },
	{ Basic, GPad_down, "../AnimalCooking/resources/images/Menu/ButtonUIMando/downButton.png" },
	{ Basic, GPad_left, "../AnimalCooking/resources/images/Menu/ButtonUIMando/leftButton.png" },
	{ Basic, GPad_right, "../AnimalCooking/resources/images/Menu/ButtonUIMando/rightButton.png"},
	{ Basic, GPad_r1, "../AnimalCooking/resources/images/Menu/ButtonUIMando/rbButton.png"},
	{ Basic, GPad_l1,"../AnimalCooking/resources/images/Menu/ButtonUIMando/lbButton.png" },
	{ Basic, GPad_r3, "../AnimalCooking/resources/images/Menu/ButtonUIMando/rsButton.png" },
	{ Basic, GPad_l3, "../AnimalCooking/resources/images/Menu/ButtonUIMando/lsButton.png" },
	{ Basic, GPad_start, "../AnimalCooking/resources/images/Menu/ButtonUIMando/startButton.png" },
	{ Basic, GPad_back, "../AnimalCooking/resources/images/Menu/ButtonUIMando/selectButton.png" },
	{ Basic, GPad_circle, "../AnimalCooking/resources/images/Menu/ButtonUIMando/circleButton.png" },
	{ Basic, GPad_box,"../AnimalCooking/resources/images/Menu/ButtonUIMando/squareButton.png" },
	{ Basic, GPad_triangle, "../AnimalCooking/resources/images/Menu/ButtonUIMando/triangleButton.png" },

	//---->Config<---------

	{Basic, Config_Background,"../AnimalCooking/resources/images/ConfigMenu/background.png"},
	{Basic, Config_FullscreenFocusedText,"../AnimalCooking/resources/images/ConfigMenu/fullScreenPink.png"},
	{Basic, Config_FullscreenUnFocusedText,"../AnimalCooking/resources/images/ConfigMenu/fullScreen.png"},
	{Basic, Config_ReminderFocusedText,"../AnimalCooking/resources/images/ConfigMenu/keyRemPink.png"},
	{Basic, Config_ReminderUnFocusedText,"../AnimalCooking/resources/images/ConfigMenu/keyRem.png"},
	{Basic, Config_Tick,"../AnimalCooking/resources/images/ConfigMenu/buttonwithTick.png"},
	{Basic, Config_UnTicked,"../AnimalCooking/resources/images/ConfigMenu/button.png"},
	{Basic, Config_MusicIcon,"../AnimalCooking/resources/images/ConfigMenu/musicIcon.png"},
	{Basic, Config_MusicVolumeTitle,"../AnimalCooking/resources/images/ConfigMenu/musicVolume.png"},
	{Basic, Config_OptionsTitle,"../AnimalCooking/resources/images/ConfigMenu/options.png"},
	{Basic, Config_Panel,"../AnimalCooking/resources/images/ConfigMenu/panel.png"},
	{Basic, Config_Player1,"../AnimalCooking/resources/images/ConfigMenu/player1.png"},
	{Basic, Config_Player2,"../AnimalCooking/resources/images/ConfigMenu/player2.png"},
	{Basic, Config_SliderMovPoint,"../AnimalCooking/resources/images/ConfigMenu/selector.png"},
	{Basic, Config_SliderMovPointSelected,"../AnimalCooking/resources/images/ConfigMenu/selectorSelect.png"},
	{Basic, Config_Slider,"../AnimalCooking/resources/images/ConfigMenu/slider.png"},
	{Basic, Config_SliderSelected,"../AnimalCooking/resources/images/ConfigMenu/sliderSelect.png"},
	{Basic, Config_SoundIcon,"../AnimalCooking/resources/images/ConfigMenu/soundIcon.png"},
	{Basic, Config_SoundVolumeTitle,"../AnimalCooking/resources/images/ConfigMenu/soundVolume.png"},

	//CreditState-----------
	{Basic,LogoTenByTen,"../AnimalCooking/resources/images/1010.png"},

	{AllLevels, Plato,"../AnimalCooking/resources/images/Cocina/pickable/plato.png"},
	{AllLevels, Suelo,"../AnimalCooking/resources/images/Cocina/sueloCocina.png"},
	{AllLevels, NieveCollider,"../AnimalCooking/resources/images/Cocina/nieve.png"},
	{AllLevels, Hielo,"../AnimalCooking/resources/images/Cocina/hielo.png"},
	{AllLevels, IslaPequenaNieve,"../AnimalCooking/resources/images/Cocina/Nieve/islotePequeno.png"},
	{AllLevels, IslaGrandeNieve,"../AnimalCooking/resources/images/Cocina/Nieve/isloteGrande.png"},
	{AllLevels, IslaMedianaNieve,"../AnimalCooking/resources/images/Cocina/Nieve/isloteMdiano.png"},
	{AllLevels, SoloNieve,"../AnimalCooking/resources/images/Cocina/Nieve/nieveGrande.png"},
	{AllLevels, SoloHielo,"../AnimalCooking/resources/images/Cocina/Nieve/HieloGrande.png"},
	{AllLevels, Hierba,"../AnimalCooking/resources/images/Cocina/sueloHierba.png"},
	{AllLevels, HierbaOtono,"../AnimalCooking/resources/images/Cocina/sueloHierbaOtono.jpg"},
	{AllLevels, HierbaInvierno,"../AnimalCooking/resources/images/Cocina/sueloHierba2.png"},
	{AllLevels, HierbaPrimavera,"../AnimalCooking/resources/images/Cocina/sueloHierba3.png"},
	{AllLevels, OvenOFF,"../AnimalCooking/resources/images/Cocina/cookers/hornoOff.png"},
	{AllLevels, OvenDerOFF,"../AnimalCooking/resources/images/Cocina/cookers/hornoDchaOff.png"},
	{AllLevels, OvenIzqOFF,"../AnimalCooking/resources/images/Cocina/cookers/hornoIzqOff.png"},
	{AllLevels, OvenOFFBordes,"../AnimalCooking/resources/images/Cocina/cookers/hornoOffBordes.png"},
	{AllLevels, OvenBordeDerOFF,"../AnimalCooking/resources/images/Cocina/cookers/hornoBordeDerOff.png"},
	{AllLevels, SkilletOFF,"../AnimalCooking/resources/images/Cocina/cookers/sartenOff.png"},
	{AllLevels, SkilletOFFEsquina,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffEsquina.png"},
	{AllLevels, SkilletOFFEsquinaIzq,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffEsquinaIzq.png"},
	{AllLevels, SkilletOFFBorde,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffBorde.png"},
	{AllLevels, SkilletOFFArribaDecoracion,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffAba.png"},
	{AllLevels, SkilletOFFArriba,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffArr.png"},
	{AllLevels, SkilletOFFBordeAmbos,"../AnimalCooking/resources/images/Cocina/cookers/sartenOffBordeAmbos.png"},

	{AllLevels, Platera,"../AnimalCooking/resources/images/Cocina/platos.png"},
	{AllLevels, PlateraBordeDerecha,"../AnimalCooking/resources/images/Cocina/platosDcha.png"},
	{AllLevels, PlateraBordeSoloDerecha,"../AnimalCooking/resources/images/Cocina/platosBordeDer.png"},
	{AllLevels, PlatosBordes,"../AnimalCooking/resources/images/Cocina/platosBordes.png"},
	{ AllLevels, PlatosVer,"../AnimalCooking/resources/images/Cocina/platosVer.png" },
	{AllLevels, PlatosVerDosBordes,"../AnimalCooking/resources/images/Cocina/platosVerDosBordes.png"},
	{ AllLevels, PlatosEsqSupDer,"../AnimalCooking/resources/images/Cocina/platosEsqSD.png" },
	{ AllLevels, PlatosAislados,"../AnimalCooking/resources/images/Cocina/PlatosAislado.png" },
	{AllLevels, Muro,"../AnimalCooking/resources/images/Cocina/muro.png"},
	{AllLevels, Muro1,"../AnimalCooking/resources/images/Cocina/muro1.png"},
	{AllLevels, ParedCocina,"../AnimalCooking/resources/images/Cocina/paredCocina.png"},
	{AllLevels, Valla,"../AnimalCooking/resources/images/Cocina/valla.png"},
	{AllLevels, VallaFinal,"../AnimalCooking/resources/images/Cocina/vallaFinal.png"},
	{AllLevels, VallaInicio,"../AnimalCooking/resources/images/Cocina/vallainicio.png"},
	{AllLevels, Collider,"../AnimalCooking/resources/images/Cocina/vacio.png"},
	{AllLevels, VallaAbajo,"../AnimalCooking/resources/images/Cocina/vallaAbajo.png"},
	//Utensilios
	{AllLevels, Cuchillo,"../AnimalCooking/resources/images/Cocina/pickable/cuchillo.png"},
	{AllLevels, CuchilloSucio,"../AnimalCooking/resources/images/Cocina/pickable/cuchilloSucio.png"},
	{AllLevels, Maza,"../AnimalCooking/resources/images/Cocina/pickable/maza.png"},
	{AllLevels, MazaSucia,"../AnimalCooking/resources/images/Cocina/pickable/mazaSucia.png"},
	{AllLevels, Rallador,"../AnimalCooking/resources/images/Cocina/pickable/rallador.png"},
	{AllLevels, RalladorSucio,"../AnimalCooking/resources/images/Cocina/pickable/ralladorSucio.png"},
	{AllLevels, Red,"../AnimalCooking/resources/images/Cocina/pickable/red.png"},
	{AllLevels, RedSucia,"../AnimalCooking/resources/images/Cocina/pickable/redSucia.png"},
	{AllLevels, Cubo,"../AnimalCooking/resources/images/Cocina/pickable/bucket.png"},
	{AllLevels, CuboLleno,"../AnimalCooking/resources/images/Cocina/pickable/bucketFill.png"},

	{AllLevels, Fregadero,"../AnimalCooking/resources/images/Cocina/fregadero/fregadero.png"},
	{AllLevels, FregaderoON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoOn.png"},
	{AllLevels, FregaderoFlip, "../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlip.png" },
    {AllLevels, FregaderoFlipON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlipOn.png" },
	{ AllLevels, FregaderoAbajo,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAbajo.png" },
	{AllLevels, FregaderoAbajoON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAbajoOn.png" },
	{ AllLevels, fregaderoAbajoEsq,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAbajoEsq.png" },
	{AllLevels, fregaderoAbajoEsqON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAbajoEsqON.png" },
	{AllLevels, FregaderoBordeIzq,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoIzq.png" },
	{AllLevels, FregaderoBordeIzqON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoIzqOn.png" },
	{AllLevels, FregaderoEsqDchaArr,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoEsqDchaArr.png" },
	{AllLevels, FregaderoEsqDchaArrON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoEsqDchaArrOn.png" },
	{ AllLevels, FregaderoFlipBordeArriba, "../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlipBordeArriba.png" },
	{ AllLevels, FregaderoFlipONBordeArriba,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlipOnBordeArriba.png" },
	{ AllLevels, FregaderoFlipSinIzq,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlipSinIzq.png" },
	{ AllLevels, FregaderoFlipSinIzqON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoFlipOnSinIzq.png" },
	{ AllLevels, FregaderoAislado,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAislado.png" },
	{ AllLevels, FregaderoAisladoON,"../AnimalCooking/resources/images/Cocina/fregadero/fregaderoAisladoON.png" },


	{AllLevels, Panera,"../AnimalCooking/resources/images/Cocina/foodgivers/panera.png"},
	{ AllLevels, PaneraVer,"../AnimalCooking/resources/images/Cocina/foodgivers/paneraVerticalBordes.png" },
	{ AllLevels, PaneraVerSinDer,"../AnimalCooking/resources/images/Cocina/foodgivers/paneraVerticalsinDcha.png" },
	{AllLevels, PaneraBordeDer,"../AnimalCooking/resources/images/Cocina/foodgivers/paneraBordeDerecha.png" },
	{AllLevels, Papelera,"../AnimalCooking/resources/images/Cocina/basura.png"},
	{AllLevels, CuadradoAux,"../AnimalCooking/resources/images/cuadrado.png"},
	//Barra entregas
	{AllLevels, BarraDcha,"../AnimalCooking/resources/images/Cocina/barra/barraDcha.png"},
	{AllLevels, BarraIzda,"../AnimalCooking/resources/images/Cocina/barra/barraIzq.png"},
	{AllLevels, BarraCentro,"../AnimalCooking/resources/images/Cocina/barra/barraCentro.png"},
	{AllLevels, BarraConTimbre,"../AnimalCooking/resources/images/Cocina/barra/barraCocinaCon.png"},
	{AllLevels, BarraSinTimbre,"../AnimalCooking/resources/images/Cocina/barra/barraCocinaSin.png"},
	//Menu
	{Basic,level0Menu,"../AnimalCooking/resources/images/ScreenLoader/level0Menu.png"},
	{Basic,level1Menu,"../AnimalCooking/resources/images/ScreenLoader/level1Menu.png"},
	{Basic,level2Menu,"../AnimalCooking/resources/images/ScreenLoader/level2Menu.png"},
	{Basic,level3Menu,"../AnimalCooking/resources/images/ScreenLoader/level3Menu.png"},
	{Basic,level4Menu,"../AnimalCooking/resources/images/ScreenLoader/level4Menu.png"},
	{Basic,levelExtra1,"../AnimalCooking/resources/images/ScreenLoader/level4Menu.png"},
	{Basic,level5Menu,"../AnimalCooking/resources/images/ScreenLoader/level5Menu.png"},
	{Basic,level6Menu,"../AnimalCooking/resources/images/ScreenLoader/level6Menu.png"},
	{Basic,level7Menu,"../AnimalCooking/resources/images/ScreenLoader/level7Menu.png"},
	{ Basic,level8Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level9Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,levelExtra2Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level10Menu,"../AnimalCooking/resources/images/ScreenLoader/level10Menu.png" },
	{ Basic,level11Menu,"../AnimalCooking/resources/images/ScreenLoader/level11Menu.png" },
	{ Basic,level12Menu,"../AnimalCooking/resources/images/ScreenLoader/level12Menu.png" },
	{ Basic,level13Menu,"../AnimalCooking/resources/images/ScreenLoader/level13Menu.png" },
	{ Basic,level14Menu,"../AnimalCooking/resources/images/ScreenLoader/level14Menu.png" },
	{ Basic,LevelExtra3,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{Basic,level15Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png"},
	{ Basic,level16Menu,"../AnimalCooking/resources/images/ScreenLoader/level2Menu.png" },
	{ Basic,level17Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level18Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level19Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,levelExtra4Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level20Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level21Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level22Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level23Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level24Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,levelExtra5Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level25Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level26Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level27Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level28Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },
	{ Basic,level29Menu,"../AnimalCooking/resources/images/ScreenLoader/level8Menu.png" },

	{Basic,barraScreenLoader,"../AnimalCooking/resources/images/ScreenLoader/barraCon.png"},
	{Basic,barraScreenLoaderBack,"../AnimalCooking/resources/images/ScreenLoader/barraSin.png"},
	//PauseState
	//pauseStateBackground
	{Basic,pauseStateBackground,"../AnimalCooking/resources/images/Menu/pauseState.png"},

	//Encimera
	{AllLevels,EncimeraAbajoConMantel,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoCon.png"},
	{AllLevels,EncimeraAbajoConMantelDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoConDcha.png"},
	{AllLevels,EncimeraAbajoConMantelIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoConIzq.png"},
	{AllLevels,EncimeraAbajoSinMantel,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoSin.png"},
	{AllLevels,EncimeraAbajoSinMantelDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoSinDcha.png"},
	{AllLevels,EncimeraAbajoSinMantelIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoSinIzq.png"},
	{AllLevels,EncimeraHorizConMantel,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraHorizCon.png"},
	{AllLevels,EncimeraHorizSinMantel,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraHorizSin.png"},
	{AllLevels,EncimeraVertConMantelDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertCon.png"},
	{AllLevels,EncimeraVertConMantelIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertCon.png"},
	{AllLevels,EncimeraVertSinMantelDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertSin.png"},
	{AllLevels,EncimeraVertSinMantelIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertSin.png"},
	{AllLevels,EncimeraVEsquinaInferiorIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaInferior2.png"},
	{AllLevels,EncimeraVEsquinaInferiorDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaInferior.png"},
	{AllLevels,EncimeraVEsquinaSuperiorDcha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaSuperior.png"},
	{AllLevels,EncimeraVEsquinaSuperiorIzda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaSuperior.png"},
	{AllLevels,EncimeraVConDecoracion,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertDecoracion.png" },
	{AllLevels,EncimeraHBordeDerecha,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraHorizBordeDcha.png" },
	{AllLevels,EncimeraHBordeIzquierda,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraHorizBordeIzq.png" },
	{ AllLevels,EncimeraVertAbajo,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertAbajo.png" },
	{AllLevels,EncimeraAbajoCont,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraAbajoCont.png" },
		
	{ AllLevels,EncimeraVertSin_SinBordeIzq,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertSin_SinBordeIzq.png" },
	{ AllLevels,EncimeraVertSin_SinBordeDer,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVertSin_SinBordeDer.png" },
	{ AllLevels,EncimeraVEsquinaSuperior_SinBordeIzq,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaSuperior_SinBordeIzq.png" },
	{ AllLevels,EncimeraVEsquinaSuperior_SinBordeDer,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaSuperior_SinBordeDer.png" },
	{ AllLevels,EncimeraHorizConBordes,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraHorizConBordes.png" },
	{ AllLevels,EncimeraDerVertCon,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraDerVertCon.png" },
	{ AllLevels,EncimeraIzqVertCon,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraIzqVertCon.png" },
	{ AllLevels,EncimeraVEsquinaSuperior_SinBordes,"../AnimalCooking/resources/images/Cocina/encimeras/encimeraVEsquinaSuperior_SinBordes.png" },

	//Esquinas
	{AllLevels,EsquinaSupDchaCopas,"../AnimalCooking/resources/images/Cocina/esquinas/esquina1-1.png"},
	{AllLevels,EsquinaSupIzdaCopas,"../AnimalCooking/resources/images/Cocina/esquinas/esquina1-2.png"},
	{AllLevels,EsquinaSupDchaVino,"../AnimalCooking/resources/images/Cocina/esquinas/esquina2-1.png"},
	{AllLevels,EsquinaSupIzdaVino,"../AnimalCooking/resources/images/Cocina/esquinas/esquina2-2.png"},
	{AllLevels,EsquinaSupDchaAgua,"../AnimalCooking/resources/images/Cocina/esquinas/esquina3-1.png"},
	{AllLevels,EsquinaSupIzdaAgua,"../AnimalCooking/resources/images/Cocina/esquinas/esquina3-2.png"},
	{AllLevels,EsquinaSupDchaVacia,"../AnimalCooking/resources/images/Cocina/esquinas/esquina4-1.png"},
	{AllLevels,EsquinaSupIzdaVacia,"../AnimalCooking/resources/images/Cocina/esquinas/esquina4-2.png"},
	{ AllLevels,EsquinaInfIzqVaciaDecoracion,"../AnimalCooking/resources/images/Cocina/esquinas/esquina-abajo.png" },
	{ AllLevels,EsquinaInfDerVaciaDecoracion,"../AnimalCooking/resources/images/Cocina/esquinas/esquina-abajo-2.png" },
	{ AllLevels,EsquinaSupIzqSinBordeDer,"../AnimalCooking/resources/images/Cocina/esquinas/esquina4-2_SinBordeDer.png" },


	//Pedidos--------------------------------------------------------------
	{Basic,Bocadillo,"../AnimalCooking/resources/images/Pedidos/bocadillo.png"},
	{AllLevels,SaladOrder,"../AnimalCooking/resources/images/Pedidos/ensalada.png"},
	{AllLevels,Salad1Order,"../AnimalCooking/resources/images/Pedidos/ensalada1.png"},
	{AllLevels,Salad2Order,"../AnimalCooking/resources/images/Pedidos/ensalada2.png"},
	{AllLevels,Salad3Order,"../AnimalCooking/resources/images/Pedidos/ensalada3.png"},
	{AllLevels,Salad4Order,"../AnimalCooking/resources/images/Pedidos/ensalada4.png"},
	{AllLevels,BurgerOrder,"../AnimalCooking/resources/images/Pedidos/hamburguesa.png"},
	{AllLevels,Burger1Order,"../AnimalCooking/resources/images/Pedidos/hamburguesa1.png"},
	{AllLevels,Burger2Order,"../AnimalCooking/resources/images/Pedidos/hamburguesa2.png"},
	{AllLevels,Burger3Order,"../AnimalCooking/resources/images/Pedidos/hamburguesa3.png"},
	{ AllLevels,PizzaOrder,"../AnimalCooking/resources/images/Pedidos/pizza.png" },
	{ AllLevels,Pizza1Order,"../AnimalCooking/resources/images/Pedidos/pizza1.png" },
	{ AllLevels,Pizza2Order,"../AnimalCooking/resources/images/Pedidos/pizza2.png" },
	{ AllLevels,Pizza3Order,"../AnimalCooking/resources/images/Pedidos/pizza3.png" },
	{ AllLevels,Pizza4Order,"../AnimalCooking/resources/images/Pedidos/pizza4.png" },
	{AllLevels,Pizza5Order,"../AnimalCooking/resources/images/Pedidos/pizza5.png"},
	{AllLevels,RoastOrder,"../AnimalCooking/resources/images/Pedidos/asado.png"},
	{AllLevels,Roast1Order,"../AnimalCooking/resources/images/Pedidos/asado1.png"},
	{AllLevels,Roast2Order,"../AnimalCooking/resources/images/Pedidos/asado2.png"},
	{AllLevels,Roast3Order,"../AnimalCooking/resources/images/Pedidos/asado3.png"},
	{AllLevels,RiceDishOrder,"../AnimalCooking/resources/images/Pedidos/arrozCasa.png"},
	{AllLevels,RisottoOrder,"../AnimalCooking/resources/images/Pedidos/risotto.png"},
	{AllLevels,CookedFishOrder,"../AnimalCooking/resources/images/Pedidos/pescadoAlHorno.png"},
	{AllLevels,FriedVegsOrder,"../AnimalCooking/resources/images/Pedidos/verdurasFritas.png"},
	{AllLevels,FriedVegsOrder1,"../AnimalCooking/resources/images/Pedidos/verdurasFritas1.png"},
	{AllLevels,FriedVegsOrder2,"../AnimalCooking/resources/images/Pedidos/verdurasFritas2.png"},
	{AllLevels,BakedChickenOrder,"../AnimalCooking/resources/images/Pedidos/polloAsado.png"},
	{AllLevels,BakedChicken1Order,"../AnimalCooking/resources/images/Pedidos/polloAsado1.png"},
	{AllLevels,BakedChicken2Order,"../AnimalCooking/resources/images/Pedidos/polloAsado2.png"},
	{AllLevels,FrenchFriesOrder,"../AnimalCooking/resources/images/Pedidos/patatasFristas.png"},
	{AllLevels,CookedClamsOrder,"../AnimalCooking/resources/images/Pedidos/vieira.png"},
	{ AllLevels,RiceAndClamsOrder,"../AnimalCooking/resources/images/Pedidos/mariscoConArroz.png" },
	{ AllLevels,FishOnStickOrder,"../AnimalCooking/resources/images/Pedidos/pescadoPalo.png" },
	{ AllLevels,FishAndChipsOrder,"../AnimalCooking/resources/images/Pedidos/fishChips.png" },
	{ AllLevels,FishBurgerOrder,"../AnimalCooking/resources/images/Pedidos/hamburguesaPescado.png" },
	{ AllLevels,Rice1Order,"../AnimalCooking/resources/images/Pedidos/arrozConTomate.png" },
	{ AllLevels,Rice2Order,"../AnimalCooking/resources/images/Pedidos/arrozPescado.png" },
	{ AllLevels,IcedCookedFishOrder,"../AnimalCooking/resources/images/Pedidos/pescadoAlHornoHiel.png" },
	{ AllLevels,IcedFishOnStickOrder,"../AnimalCooking/resources/images/Pedidos/pescadoPaloHielo.png" },
	{ AllLevels,IcedFishAndChipsOrder,"../AnimalCooking/resources/images/Pedidos/fishChipsHielo.png" },
	{ AllLevels,IcedFishBurgerOrder,"../AnimalCooking/resources/images/Pedidos/hamburguesaPescadoHielo.png" },
	{ AllLevels,IcedRice1Order,"../AnimalCooking/resources/images/Pedidos/arrozConTomateHielo.png" },
	{ AllLevels,IcedRice2Order,"../AnimalCooking/resources/images/Pedidos/arrozPescadoHielo.png" },
	{ AllLevels,IcedRiceAndClamsOrder,"../AnimalCooking/resources/images/Pedidos/mariscoConArrozHielo.png" },
	{ AllLevels,IcedRiceDishOrder,"../AnimalCooking/resources/images/Pedidos/arrozCasaHielo.png" },
	{ AllLevels,Sushi1Order,"../AnimalCooking/resources/images/Pedidos/sushi1.png" },
	{ AllLevels,Sushi2Order,"../AnimalCooking/resources/images/Pedidos/sushi2.png" },
	{ AllLevels,Sushi3Order,"../AnimalCooking/resources/images/Pedidos/sushi3.png" },
	{ AllLevels,Sushi4Order,"../AnimalCooking/resources/images/Pedidos/sushi4.png" },
	{ AllLevels,Sushi5Order,"../AnimalCooking/resources/images/Pedidos/sushi45.png" },
	{ AllLevels,OnigiriOrder,"../AnimalCooking/resources/images/Pedidos/onigiri.png" },
	{ AllLevels,Teriyaki1Order,"../AnimalCooking/resources/images/Pedidos/teriyaki1.png" },
	{ AllLevels,Teriyaki2Order,"../AnimalCooking/resources/images/Pedidos/teriyaki2.png" },
	{ AllLevels,Teriyaki3Order,"../AnimalCooking/resources/images/Pedidos/teriyaki3.png" },
	{AllLevels,Teriyaki4Order,"../AnimalCooking/resources/images/Pedidos/teriyaki4.png"},
	{ AllLevels,PerritoOrder,"../AnimalCooking/resources/images/Pedidos/hotdog.png" },
	{ AllLevels,Perrito1Order,"../AnimalCooking/resources/images/Pedidos/hotdog1.png" },
	{ AllLevels,Perrito2Order,"../AnimalCooking/resources/images/Pedidos/hotdog2.png" },
	{ AllLevels,Perrito3Order,"../AnimalCooking/resources/images/Pedidos/hotdog3.png" },


	//Foods-----------------------------------------------------------------
	{AllLevels, TextureId::PoopT,"../AnimalCooking/resources/images/Foods/caca.png"},
	{AllLevels, TextureId::SlicedTomatoT,"../AnimalCooking/resources/images/Foods/tomateCortado.png"},
	{AllLevels, TextureId::SlicedLettuceT,"../AnimalCooking/resources/images/Foods/lechugaCortada.png"},
	{AllLevels, TextureId::SlicedOnionT,"../AnimalCooking/resources/images/Foods/cebollaCortado.png"},
	{AllLevels, TextureId::SlicedMeatT,"../AnimalCooking/resources/images/Foods/carneCortado.png"},
	{AllLevels, TextureId::MashedMeatT,"../AnimalCooking/resources/images/Foods/carneAplastada.png"},
	{AllLevels, TextureId::SlicedCheeseT,"../AnimalCooking/resources/images/Foods/quesoCortado.png"},
	{AllLevels, TextureId::GratedCheeseT,"../AnimalCooking/resources/images/Foods/quesoRallado.png"},
	{AllLevels, TextureId::SlicedPotatoT,"../AnimalCooking/resources/images/Foods/patataCortada.png"},
	{AllLevels, TextureId::SlicedSausageT,"../AnimalCooking/resources/images/Foods/salchichaCortada.png"},
	{AllLevels, TextureId::SlicedCarrotT,"../AnimalCooking/resources/images/Foods/zanahoriaCortada.png"},
	{AllLevels, TextureId::CaughtSausageT,"../AnimalCooking/resources/images/Foods/salchichaRed.png"},
	{AllLevels, TextureId::SlicedMushroomT,"../AnimalCooking/resources/images/Foods/champinonCortada.png"},
	{AllLevels, TextureId::CaughtFishT,"../AnimalCooking/resources/images/Foods/rescadoRed.png"},
	{AllLevels, TextureId::SlicedChickenT,"../AnimalCooking/resources/images/Foods/polloCortado.png"},
	{AllLevels, TextureId::CaughtClamT,"../AnimalCooking/resources/images/Foods/vieraRed.png"},
	{ AllLevels, TextureId::IceT,"../AnimalCooking/resources/images/Foods/hielo.png" },
	{ AllLevels, TextureId::SlicedFishT,"../AnimalCooking/resources/images/Foods/pescadoCortado.png" },
	{AllLevels, TextureId::RiceT,"../AnimalCooking/resources/images/Foods/arroz.png"},
	{AllLevels, TextureId::BreadBurgerT,"../AnimalCooking/resources/images/Foods/panHamburguesa.png"},
	{AllLevels, TextureId::BreadHotDogT,"../AnimalCooking/resources/images/Foods/panPerrito.png"},
	{AllLevels, TextureId::PizzaMassT,"../AnimalCooking/resources/images/Foods/masa.png"},
	{ AllLevels, TextureId::GratedMeatT,"../AnimalCooking/resources/images/Foods/carneRallador.png" },
	{AllLevels, TextureId::SaladT,"../AnimalCooking/resources/images/Foods/ensalada.png"},
	{AllLevels, TextureId::Salad1T,"../AnimalCooking/resources/images/Foods/ensalada1.png"},
	{AllLevels, TextureId::Salad2T,"../AnimalCooking/resources/images/Foods/ensalada2.png"},
	{AllLevels, TextureId::Salad3T,"../AnimalCooking/resources/images/Foods/ensalada3.png"},
	{AllLevels, TextureId::Salad4T,"../AnimalCooking/resources/images/Foods/ensalada4.png"},
	{AllLevels, TextureId::BurgerT,"../AnimalCooking/resources/images/Foods/hamburguesa.png"},
	{AllLevels, TextureId::Burger1T,"../AnimalCooking/resources/images/Foods/hamburguesa1.png"},
	{AllLevels, TextureId::Burger2T,"../AnimalCooking/resources/images/Foods/hamburguesa2.png"},
	{AllLevels, TextureId::Burger3T,"../AnimalCooking/resources/images/Foods/hamburguesa3.png"},
	{AllLevels, TextureId::PizzaT,"../AnimalCooking/resources/images/Foods/pizza.png"},
	{ AllLevels, TextureId::Pizza1T,"../AnimalCooking/resources/images/Foods/pizza1.png" },
	{ AllLevels, TextureId::Pizza2T,"../AnimalCooking/resources/images/Foods/pizza2.png" },
	{ AllLevels, TextureId::Pizza3T,"../AnimalCooking/resources/images/Foods/pizza3.png" },
	{ AllLevels, TextureId::Pizza4T,"../AnimalCooking/resources/images/Foods/pizza4.png" },
	{ AllLevels, TextureId::Pizza5T,"../AnimalCooking/resources/images/Foods/pizza5.png" },
	{AllLevels, TextureId::RoastT,"../AnimalCooking/resources/images/Foods/asado.png"},
	{AllLevels, TextureId::Roast1T,"../AnimalCooking/resources/images/Foods/asado1.png"},
	{AllLevels, TextureId::Roast2T,"../AnimalCooking/resources/images/Foods/asado2.png"},
	{AllLevels, TextureId::Roast3T,"../AnimalCooking/resources/images/Foods/asado3.png"},
	{AllLevels, TextureId::RiceDishT,"../AnimalCooking/resources/images/Foods/arrozDeLaCasa.png"},
	{AllLevels, TextureId::RisottoT,"../AnimalCooking/resources/images/Foods/risotto.png"},
	{AllLevels, TextureId::CookedFishT,"../AnimalCooking/resources/images/Foods/pescadoAlHorno.png"},
	{AllLevels, TextureId::FriedVegsT,"../AnimalCooking/resources/images/Foods/verdurasFritas.png"},
	{AllLevels, TextureId::FriedVegs1T,"../AnimalCooking/resources/images/Foods/verdurasFritas1.png"},
	{AllLevels, TextureId::FriedVegs2T,"../AnimalCooking/resources/images/Foods/verdurasFritas2.png"},
	{AllLevels, TextureId::BakedChickenT,"../AnimalCooking/resources/images/Foods/pollo.png"},
	{AllLevels, TextureId::BakedChicken1T,"../AnimalCooking/resources/images/Foods/pollo1.png"},
	{AllLevels, TextureId::BakedChicken2T,"../AnimalCooking/resources/images/Foods/pollo2.png"},
	{AllLevels, TextureId::FrenchFriesT,"../AnimalCooking/resources/images/Foods/patatasFritas.png"},
	{AllLevels, TextureId::CookedClamsT,"../AnimalCooking/resources/images/Foods/vieraGratinada.png"},
	{AllLevels, TextureId::RiceAndClamsT,"../AnimalCooking/resources/images/Foods/mariscoConArroz.png"},
	{AllLevels, TextureId::MashedMeatSkilletT,"../AnimalCooking/resources/images/Foods/carneSarten.png"},
	{AllLevels, TextureId::CaughtSausageSkilletT,"../AnimalCooking/resources/images/Foods/salchichaSarten.png"},
	{AllLevels, TextureId::SlicedPotatoSkilletT,"../AnimalCooking/resources/images/Foods/patatasSarten.png"},
	{AllLevels, TextureId::DressT,"../AnimalCooking/resources/images/Foods/dress.png"},
	{ AllLevels, TextureId::MashedTomatoT,"../AnimalCooking/resources/images/Foods/tomateAplastado.png" },
	{ AllLevels, TextureId::FishSkilletT,"../AnimalCooking/resources/images/Foods/pescadoSarten.png" },
	{ AllLevels, TextureId::FishOnStickT,"../AnimalCooking/resources/images/Foods/pescadoPalo.png" },
	{ AllLevels, TextureId::FishAndChipsT,"../AnimalCooking/resources/images/Foods/fishChips.png" },
	{ AllLevels, TextureId::FishBurgerT,"../AnimalCooking/resources/images/Foods/hamburguesaPescado.png" },
	{ AllLevels, TextureId::Rice1T,"../AnimalCooking/resources/images/Foods/arrozContomate.png" },
	{ AllLevels, TextureId::Rice2T,"../AnimalCooking/resources/images/Foods/arrozPescado.png" },
	{ AllLevels, TextureId::IcedCookedFishT,"../AnimalCooking/resources/images/Foods/pescadoAlHornoHielo.png" },
	{ AllLevels, TextureId::IcedFishOnStickT,"../AnimalCooking/resources/images/Foods/pescadoPaloHielo.png" },
	{ AllLevels, TextureId::IcedFishAndChipsT,"../AnimalCooking/resources/images/Foods/fishChipsHielo.png" },
	{ AllLevels, TextureId::IcedFishBurgerT,"../AnimalCooking/resources/images/Foods/hamburguesaPescadoHielo.png" },
	{ AllLevels, TextureId::IcedRice1T,"../AnimalCooking/resources/images/Foods/arrozContomateHielo.png" },
	{ AllLevels, TextureId::IcedRice2T,"../AnimalCooking/resources/images/Foods/arrozPescadoHielo.png" },
	{ AllLevels, TextureId::IcedRiceAndClamsT,"../AnimalCooking/resources/images/Foods/mariscoConArrozHielo.png" },
	{ AllLevels, TextureId::IcedRiceDishT,"../AnimalCooking/resources/images/Foods/arrozDeLaCasaHielo.png"},

	{ AllLevels, TextureId::NoriT,"../AnimalCooking/resources/images/Foods/alga.png" },
	{ AllLevels, TextureId::SlicedSalmonT,"../AnimalCooking/resources/images/Foods/salmonCortado.png" },
	{ AllLevels, TextureId::SlicedAvocadoT,"../AnimalCooking/resources/images/Foods/aguacate.png" },
	{ AllLevels, TextureId::GratedChickenT,"../AnimalCooking/resources/images/Foods/polloRallador.png" },
	{ AllLevels, TextureId::GratedSkilletChickenT,"../AnimalCooking/resources/images/Foods/polloRalladoSarten.png" },
	{ AllLevels, TextureId::Sushi1T,"../AnimalCooking/resources/images/Foods/sushi1.png" },
	{ AllLevels, TextureId::Sushi2T,"../AnimalCooking/resources/images/Foods/sushi2.png" },
	{ AllLevels, TextureId::Sushi3T,"../AnimalCooking/resources/images/Foods/sushi3.png" },
	{ AllLevels, TextureId::Sushi4T,"../AnimalCooking/resources/images/Foods/sushi4.png" },
	{ AllLevels, TextureId::Sushi5T,"../AnimalCooking/resources/images/Foods/sushi5.png" },
	{ AllLevels, TextureId::OnigiriT,"../AnimalCooking/resources/images/Foods/onigiri.png" },
	{ AllLevels, TextureId::Teriyaki1T,"../AnimalCooking/resources/images/Foods/teriyaki1.png" },
	{ AllLevels, TextureId::Teriyaki2T,"../AnimalCooking/resources/images/Foods/teriyaki2.png" },
	{ AllLevels, TextureId::Teriyaki3T,"../AnimalCooking/resources/images/Foods/teriyaki3.png" },
	{ AllLevels, TextureId::Teriyaki4T,"../AnimalCooking/resources/images/Foods/teriyaki4.png" },

	

	{ AllLevels, TextureId::PerritoT,"../AnimalCooking/resources/images/Foods/perritoCaliente.png" },
	{ AllLevels, TextureId::Perrito1T,"../AnimalCooking/resources/images/Foods/perritoCaliente1.png" },
	{ AllLevels, TextureId::Perrito2T,"../AnimalCooking/resources/images/Foods/perritoCaliente2.png" },
	{ AllLevels, TextureId::Perrito3T,"../AnimalCooking/resources/images/Foods/perritoCaliente3.png" },

	//FeedBack---------------------------------------------------------------
		//Food
		{AllLevels, PoopFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/caca.png"},
		{AllLevels, SlicedTomatoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/tomateCortado.png"},
		{AllLevels, SlicedLettuceFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/lechugaCortada.png"},
		{AllLevels, SlicedOnionFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/cebollaCortado.png"},
		{AllLevels, SlicedMeatFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/carneCortado.png"},
		{AllLevels, MashedMeatFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/carneAplastada.png"},
		{AllLevels, SlicedCheeseFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/quesoCortado.png"},
		{AllLevels, GratedCheeseFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/quesoRallado.png"},
		{AllLevels, SlicedPotatoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/patataCortada.png"},
		{AllLevels, SlicedSausageFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/salchichaCortada.png"},
		{AllLevels, SlicedCarrotFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/zanahoriaCortada.png"},
		{AllLevels, CaughtSausageFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/salchichaRed.png"},
		{AllLevels, SlicedMushroomFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/champinonCortada.png"},
		{AllLevels, CaughtFishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/rescadoRed.png"},
		{AllLevels, SlicedChickenFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/polloCortado.png"},
	    { AllLevels, CaughtClamFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/vieraRed.png" },
		{ AllLevels, SlicedFishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoCortado.png" },
		{AllLevels, IceFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hielo.png"},
		{AllLevels, RiceFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arroz.png"},
		{AllLevels, BreadBurgerFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/panHamburguesa.png"},
		{AllLevels, BreadHotDogFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/panPerrito.png"},
		{AllLevels, PizzaMassFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/masa.png"},
	    { AllLevels, GratedMeatFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/carneRallador.png" },
		{AllLevels, SaladFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/ensalada.png"},
		{AllLevels, Salad1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/ensalada1.png"},
		{AllLevels, Salad2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/ensalada2.png"},
		{AllLevels, Salad3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/ensalada3.png"},
		{AllLevels, Salad4FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/ensalada4.png"},
		{AllLevels, BurgerFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesa.png"},
		{AllLevels, Burger1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesa1.png"},
		{AllLevels, Burger2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesa2.png"},
		{AllLevels, Burger3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesa3.png"},
		{AllLevels, PizzaFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png"},
	    { AllLevels, Pizza1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png" },
	    { AllLevels, Pizza2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png" },
	    { AllLevels, Pizza3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png" },
	    { AllLevels, Pizza4FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png" },
	    { AllLevels, Pizza5FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pizza.png" },
		{AllLevels, RoastFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/asado.png"},
		{AllLevels, Roast1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/asado1.png"},
		{AllLevels, Roast2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/asado2.png"},
		{AllLevels, Roast3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/asado3.png"},
		{AllLevels, RiceDishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozDeLaCasa.png"},
		{AllLevels, RisottoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/risotto.png"},
		{AllLevels, CookedFishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoAlHorno.png"},
		{AllLevels, FriedVegsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/verdurasFritas.png"},
		{AllLevels, FriedVegs1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/verdurasFritas1.png"},
		{AllLevels, FriedVegs2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/verdurasFritas2.png"},
		{AllLevels, BakedChickenFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pollo.png"},
		{AllLevels, BakedChicken1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pollo1.png"},
		{AllLevels, BakedChicken2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pollo2.png"},
		{AllLevels, FrenchFriesFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/patatasFritas.png"},
		{AllLevels, CookedClamsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/vieraGratinada.png"},
		{AllLevels, RiceAndClamsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/mariscoConArroz.png"},
		{AllLevels, MashedMeatSkilletFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/carneAplastada.png"},
		{AllLevels, CaughtSausageSkilletFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/salchichaSarten.png"},
		{AllLevels, SlicedPotatoSkilletFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/patatasSarten.png"},
		{AllLevels, DressFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/dress.png"},
		{ AllLevels, MashedTomatoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/tomateAplastado.png" },
		{ AllLevels, FishSkilletFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoSarten.png" },
		{ AllLevels, FishOnStickFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoPalo.png" },
		{ AllLevels, FishAndChipsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/fishChips.png" },
		{ AllLevels, FishBurgerFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesaPescado.png" },
		{ AllLevels, Rice1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozContomate.png" },
		{ AllLevels, Rice2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozPescado.png" },
		{ AllLevels, IcedCookedFishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoAlHornoHielo.png" },
		{ AllLevels, IcedFishOnStickFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/pescadoPaloHielo.png" },
		{ AllLevels, IcedFishAndChipsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/fishChipsHielo.png" },
		{ AllLevels, IcedFishBurgerFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/hamburguesaPescadoHielo.png" },
		{ AllLevels, IcedRice1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozContomateHielo.png" },
		{ AllLevels, IcedRice2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozDeLaCasaHielo.png" },
		{ AllLevels, IcedRiceAndClamsFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/mariscoConArrozHielo.png" },
		{AllLevels, IcedRiceDishFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/arrozPescadoHielo.png"},

		{ AllLevels, NoriFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/alga.png" },
		{ AllLevels, SlicedSalmonFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/salmonCortado.png" },
		{ AllLevels, GratedChickenFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/polloRallador.png" },
		{ AllLevels, GratedSkilletChickenFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/polloRalladoSarten.png" },
		{ AllLevels, SlicedAvocadoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/aguacate.png" },
		{ AllLevels, Sushi1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/sushi1.png" },
		{ AllLevels, Sushi2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/sushi2.png" },
		{ AllLevels, Sushi3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/sushi3.png" },
		{ AllLevels, Sushi4FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/sushi4.png" },
		{ AllLevels, Sushi5FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/sushi5.png" },
		{ AllLevels, OnigiriFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/onigiri.png" },
		{ AllLevels, Teriyaki1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/teriyaki1.png" },
		{ AllLevels, Teriyaki2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/teriyaki2.png" },
		{ AllLevels, Teriyaki3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/teriyaki3.png" },
		{ AllLevels, Teriyaki4FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/teriyaki4.png" },
	    { AllLevels, PerritoFeedBack,"../AnimalCooking/resources/images/FeedBack/Food/perritoCaliente.png" },
	    { AllLevels, Perrito1FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/perritoCaliente.png" },
	    { AllLevels, Perrito2FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/perritoCaliente2.png" },
	    { AllLevels, Perrito3FeedBack,"../AnimalCooking/resources/images/FeedBack/Food/perritoCaliente3.png" },

		//Utensil
		{AllLevels, CuchilloFeedBack,"../AnimalCooking/resources/images/FeedBack/Utensil/cuchilloFeedBack.png"},
		{AllLevels, MazoFeedBack,"../AnimalCooking/resources/images/FeedBack/Utensil/mazaFeedBack.png"},
		{AllLevels, RedFeedBack,"../AnimalCooking/resources/images/FeedBack/Utensil/redFeedBack.png"},
		{AllLevels, RalladorFeedBack,"../AnimalCooking/resources/images/FeedBack/Utensil/ralladorFeedBack.png"},
		{AllLevels, CuboFeedBack,"../AnimalCooking/resources/images/FeedBack/Utensil/bucketFeedback.png"},
		//General
		{AllLevels, PapeleraFeedBack,"../AnimalCooking/resources/images/FeedBack/General/papeleraFeedBack.png"},
		{AllLevels, PlatoFeedBack,"../AnimalCooking/resources/images/FeedBack/General/platoFeedBack.png"},
		{AllLevels, Panel,"../AnimalCooking/resources/images/FeedBack/General/panel.png"},
		{AllLevels, BordeTeclaFeedBack,"../AnimalCooking/resources/images/FeedBack/General/TeclaBorde.png"},
		{AllLevels, RellenoTeclaFeedBack,"../AnimalCooking/resources/images/FeedBack/General/TeclaRelleno.png"},

		// images level specific
		{AllLevels, Aceite,"../AnimalCooking/resources/images/Cocina/foodgivers/alino.png"},
		{ AllLevels, AceiteBordeDer,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoDcha.png" },
		{ AllLevels, AceiteBordeIzq,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoIzq.png" },
		{ AllLevels, AceiteVertical,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoVertical.png" },
		{ AllLevels, AceiteVerSinIzq,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoVerticalsinIzq.png" },
	    { AllLevels, AceiteVerSinDer,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoVerticalsinDer.png" },
		{ AllLevels, AceiteSin,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoSin.png" },
	    { AllLevels, AceiteVerticalBordeSup,"../AnimalCooking/resources/images/Cocina/foodgivers/alinoVerticalBordeSup.png" },
		{ AllLevels, Arroz,"../AnimalCooking/resources/images/Cocina/foodgivers/arrocera.png"},
	    { AllLevels, ArrozBordeSup,"../AnimalCooking/resources/images/Cocina/foodgivers/arroceraBordeSup.png" },
	    { AllLevels, ArrozSinBordeDer,"../AnimalCooking/resources/images/Cocina/foodgivers/arroceraSinBordeDer.png" },
		{ AllLevels, ArrozHor,"../AnimalCooking/resources/images/Cocina/foodgivers/arroceraHor.png" },
		{ AllLevels, ArroceraAislada,"../AnimalCooking/resources/images/Cocina/foodgivers/ArroceraAislada.png" },
		{ AllLevels, ArroceraBordes,"../AnimalCooking/resources/images/Cocina/foodgivers/ArroceraBordes.png" },
		
		{ AllLevels, horDogHBordeD,"../AnimalCooking/resources/images/Cocina/foodgivers/horDogHBordeD.png" },
		{ AllLevels, horDogHBordeI,"../AnimalCooking/resources/images/Cocina/foodgivers/horDogHBordeI.png" },
		{ AllLevels, horDogH,"../AnimalCooking/resources/images/Cocina/foodgivers/horDogH.png" },
		{ AllLevels, EncimeraMasa,"../AnimalCooking/resources/images/Cocina/foodgivers/encimeraMasa.png"},
		{ AllLevels, EncimeraMasaV,"../AnimalCooking/resources/images/Cocina/foodgivers/encimeraMasaV.png" },
		{ AllLevels, NoriFoodGiver,"../AnimalCooking/resources/images/Cocina/foodgivers/algas.png" },
		{ AllLevels, algasVDcha,"../AnimalCooking/resources/images/Cocina/foodgivers/algasVDcha.png" },
		{ AllLevels, algasHBordes,"../AnimalCooking/resources/images/Cocina/foodgivers/algaHBordes.png" },
			
		// Adversities
		{AllLevels, WarningAdversity, "../AnimalCooking/resources/images/Adversities/WarningAdversity.png"},
		{AllLevels, PlaneShadow, "../AnimalCooking/resources/images/Adversities/plane.png"},
		{ AllLevels, RainAdversity, "../AnimalCooking/resources/images/Adversities/lluvia.png" },
		{ AllLevels, HookAdversity, "../AnimalCooking/resources/images/Adversities/gancho.png" },


		//creditState
	{ Basic, woodCredits, "../AnimalCooking/resources/images/Menu/pauseStateEfecto.png" },

};

vector<Resources::SpritesheetInfo> Resources::spritesheets_{
	//
	//Botones
	{Basic, Button,"../AnimalCooking/resources/images/Menu/botones.png", 1, 3},
	{Basic, ButtonConfig,"../AnimalCooking/resources/images/Menu/botonesConfig.png", 1, 3},
	{Basic, ButtonBin,"../AnimalCooking/resources/images/Menu/botonesPapelera.png", 1, 3},
	{Basic, ReplayIcon,"../AnimalCooking/resources/images/EndState/ReplayProvisional.png", 1, 3},
	{Basic, NextLevelIcon,"../AnimalCooking/resources/images/EndState/PlayProvisional.png",1,3},
	{Basic, HomeIconEndState,"../AnimalCooking/resources/images/EndState/HomeProvisional.png",1,3},
	{Basic, HomeIconMapState,"../AnimalCooking/resources/images/Mapstate/homeMapState.png",1,2},
	{Basic, MapIcon,"../AnimalCooking/resources/images/EndState/MapProvisional.png",1,3},
	{Basic, botonPauseState,"../AnimalCooking/resources/images/Menu/botonesPauseState.png",1,3},

	{Basic, Config_BackButton,"../AnimalCooking/resources/images/ConfigMenu/backButton.png",1,3},
	{Basic, Config_CerdoClick,"../AnimalCooking/resources/images/ConfigMenu/cerdoClick.png",1,3},
	{Basic, Config_ChickenClick,"../AnimalCooking/resources/images/ConfigMenu/gallinaClick.png",1,3},
	{Basic, Config_XBoxOrPs4Icon,"../AnimalCooking/resources/images/ConfigMenu/XBOXorPS4.png", 1, 4},

	{Basic, buttonGo,"../AnimalCooking/resources/images/ScreenLoader/buttonGo.png",1,3},
	//---------
	{AllLevels, CircularTimer,"../AnimalCooking/resources/images/circleTimer.png", 1, 8},
	{AllLevels, BurnedTimer,"../AnimalCooking/resources/images/burningTimer.png", 1, 8},
	{AllLevels, OvenON,"../AnimalCooking/resources/images/Cocina/cookers/hornoOn.png", 4, 1},
	{AllLevels, OvenDerON,"../AnimalCooking/resources/images/Cocina/cookers/hornoDchaOn.png", 4, 1},
	{AllLevels, OvenIzqON,"../AnimalCooking/resources/images/Cocina/cookers/hornoIzqOn.png", 4, 1},
	{AllLevels, OvenONBordes,"../AnimalCooking/resources/images/Cocina/cookers/hornoOnBordes.png", 4, 1},
	{AllLevels, OvenBordeDerON,"../AnimalCooking/resources/images/Cocina/cookers/hornoBordeDerOn.png", 4, 1},
	{AllLevels, SkilletON,"../AnimalCooking/resources/images/Cocina/cookers/sartenOn.png", 3, 1},
	{AllLevels, SkilletONEsquina,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnEsqiuna.png", 3, 1},
	{AllLevels, SkilletONEsquinaIzq,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnEsqiunaIzq.png", 3, 1},
	{AllLevels, SkilletONBorde,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnBorde.png", 3, 1},
	{AllLevels, SkilletONArribaDecoracion,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnAba.png", 3, 1},
	{AllLevels, SkilletONArriba,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnArrpng.png", 3, 1},
	{AllLevels, SkilletONBordeAmbos,"../AnimalCooking/resources/images/Cocina/cookers/sartenOnBordeAmbos.png", 3, 1},

	{AllLevels, SmokeBurned,"../AnimalCooking/resources/images/Cocina/cookers/Humo.png", 1, 3},
	{AllLevels, PigIdle, "../AnimalCooking/resources/images/Animaciones/Cerdo/idle.png",24,8},
	{AllLevels, PigWalk, "../AnimalCooking/resources/images/Animaciones/Cerdo/andar.png",24,4},
	{AllLevels, PigAttack, "../AnimalCooking/resources/images/Animaciones/Cerdo/ataque.png",10,2},
	{AllLevels, ChickenIdle, "../AnimalCooking/resources/images/Animaciones/Gallina/idle.png",24,8},
	{AllLevels, ChickenWalk, "../AnimalCooking/resources/images/Animaciones/Gallina/andar.png",24,4},
	{AllLevels, ChickenAttack, "../AnimalCooking/resources/images/Animaciones/Gallina/ataque.png",10,2},
	{AllLevels, Tomato,"../AnimalCooking/resources/images/Ingredientes/tomate.png",3,2},
	{AllLevels, Potato,"../AnimalCooking/resources/images/Ingredientes/patata.png",3,2},
	{AllLevels, Clam,"../AnimalCooking/resources/images/Ingredientes/vieira.png",3,2},
	{AllLevels, Cheese,"../AnimalCooking/resources/images/Ingredientes/queso.png",3,2},
	{AllLevels, Meat,"../AnimalCooking/resources/images/Ingredientes/carne.png",3,2},
	{AllLevels, Lettuce,"../AnimalCooking/resources/images/Ingredientes/lechuga.png",3,2},
	{AllLevels, Mushroom,"../AnimalCooking/resources/images/Ingredientes/champi.png",3,2},
	{AllLevels, Onion,"../AnimalCooking/resources/images/Ingredientes/cebolla.png",3,2},
	{AllLevels, Fish,"../AnimalCooking/resources/images/Ingredientes/pescado.png",3,2},
	{AllLevels, Chicken,"../AnimalCooking/resources/images/Ingredientes/pollo.png",3,2},
	{AllLevels, Carrot,"../AnimalCooking/resources/images/Ingredientes/zanahoria.png",3,2},
	{AllLevels, Sausage,"../AnimalCooking/resources/images/Ingredientes/salchicha.png",3,2},
	{AllLevels, Snowman,"../AnimalCooking/resources/images/Ingredientes/frosty.png",3,2},
	{AllLevels, Salmon,"../AnimalCooking/resources/images/Ingredientes/salmon.png",3,2},
	{AllLevels, Avocado,"../AnimalCooking/resources/images/Ingredientes/aguacate.png",3,2},
	{AllLevels, Puerta,"../AnimalCooking/resources/images/Cocina/puerta2.png",1,4},
	{Basic, FireOverHeated,"../AnimalCooking/resources/images/Adversities/fuegoAdv.png",1,3},
	{Basic, LightingStrike,"../AnimalCooking/resources/images/Adversities/lighting.png",1,8},
	{Basic, LightingExplosion,"../AnimalCooking/resources/images/Adversities/explosion.png",1,7},
	{Basic, MapRestaurantButton, "../AnimalCooking/resources/images/Mapstate/MapStateBotones.png",1,3 },	//Mapstate
	{Basic, ButtonNext, "../AnimalCooking/resources/images/Mapstate/nextButton.png",1,4 },					//Mapstate
	{Basic, ButtonPrev, "../AnimalCooking/resources/images/Mapstate/prevButton.png",1,3 },					//Mapstate
	{Basic, TextureId::MapStatePlayButton, "../AnimalCooking/resources/images/Mapstate/mapStatePlayButton.png",1,3 },
	{Basic, Explosion, "../AnimalCooking/resources/images/Animaciones/Otro/humillo.png",1,7 },
	{AllLevels, Ghost, "../AnimalCooking/resources/images/Animaciones/Otro/ghost.png",1,9 },
	{ AllLevels, PidgeonAdversity, "../AnimalCooking/resources/images/Adversities/palomaSP.png",1,21 },
	{AllLevels, Blizzard, "../AnimalCooking/resources/images/Adversities/ventisca.png", 1,6},
	{AllLevels, FlowerAdversity, "../AnimalCooking/resources/images/Adversities/flores.png", 2,7}

};

vector<Resources::TextMsgInfo> Resources::messages_{

	{Basic,AntonioJesus,"Antonio Jesus Guerra Garduno",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Daniel,"Daniel Gonzalez Sellan",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,David,"David Czepiel",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Felipe,"Felipe Cuadra Plaza",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Javier,"Javier Cruz Lopez de Ochoa",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Marco,"Marco Ivan Merino Hernandez",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Nicolas,"Nicolas Fernandez Descalzo",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Pablo,"Pablo Villapun Martin",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Sandra,"Sandra Mondragon Lazaro",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Tatiana,"Tatiana Duarte Balvis",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,TextureId::MapNewGameButton,"New Game",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,TextureId::MapLoadGameButton,"Load Game",hex2sdlcolor("#FFFFFFFF"),QuarkCheese100},
	{Basic,Go,"Go",hex2sdlcolor("#000000FF"),QuarkCheese50},

	{Basic, TextureId::Back, "Return", COLOR(0xffffffff), FontId::QuarkCheese100},

	{Basic, TextureId::PickUpText, "Pick up", COLOR(0xcc636dff), FontId::QuarkCheese62},
	{Basic, TextureId::AttackText, "Attack", COLOR(0xcc636dff), FontId::QuarkCheese62},
	{Basic, TextureId::OpenText, "Open", COLOR(0xcc636dff), FontId::QuarkCheese62},
	{Basic, TextureId::FinishText, "Finish Dish", COLOR(0xcc636dff), FontId::QuarkCheese62},
	{Basic, TextureId::NextText, "Next", COLOR(0xcc636dff), FontId::QuarkCheese62},
	{Basic, TextureId::PreviousText, "Previous", COLOR(0xcc636dff), FontId::QuarkCheese62}
};


vector<Resources::MusicInfo> Resources::musics_{
	//
	{Basic, MenuInicio, "../AnimalCooking/resources/sounds/Menu_inicio.ogg"},
	{AllLevels, Level1, "../AnimalCooking/resources/sounds/Ingame piano.ogg"},
	{AllLevels, Level10, "../AnimalCooking/resources/sounds/Animal cooking winter.ogg"},
	{AllLevels, Level15, "../AnimalCooking/resources/sounds/Animal cooking japan.ogg"}
};

vector<Resources::SoundInfo> Resources::sounds_{
	//
	{AllLevels, KnifeAttack,"../AnimalCooking/resources/sounds/Cuchillo 1.wav"},
	{AllLevels, DropDish,"../AnimalCooking/resources/sounds/Dejar Plato 1.wav"}, //
	{AllLevels, CompleteDish,"../AnimalCooking/resources/sounds/Elaborar Plato 1.wav"},//
	{AllLevels, Wash,"../AnimalCooking/resources/sounds/Fregar 1.wav"},
	{AllLevels, FrySound,"../AnimalCooking/resources/sounds/Freir Loop 2.wav"},
	{AllLevels, MaceAttack,"../AnimalCooking/resources/sounds/Golpe Mazo 1.wav"},
	{AllLevels, MicroWave,"../AnimalCooking/resources/sounds/Microondas Beep.wav"},
	{AllLevels, Door,"../AnimalCooking/resources/sounds/Puerta 1.wav"},
	{AllLevels, FrySoundBurned,"../AnimalCooking/resources/sounds/Freir Quemar.wav" },
	{AllLevels, Bin,"../AnimalCooking/resources/sounds/Basura 2.wav" },
	{AllLevels, PickUp,"../AnimalCooking/resources/sounds/Bop nuevo 4.wav" },
	{AllLevels, Drop,"../AnimalCooking/resources/sounds/Dejar Caer 4.wav" },
	{AllLevels, AttackMiss,"../AnimalCooking/resources/sounds/Golpe fallido 3.wav" },
	{AllLevels, BurnedBeep,"../AnimalCooking/resources/sounds/Microondas Temporizador.wav" },
	{AllLevels, CookedFood,"../AnimalCooking/resources/sounds/Microondas Beep.wav" },
	{Basic, IngredientSpawned,"../AnimalCooking/resources/sounds/Aparece Ingrediente 2-Poly.wav" },
	{Basic, OrderRecieved,"../AnimalCooking/resources/sounds/Timbre 2.wav" },
	{Basic, PlaneSound,"../AnimalCooking/resources/sounds/planeSound.wav"},
	{Basic, RainSound,"../AnimalCooking/resources/sounds/rainSound.wav"},
	{Basic, ThunderSound,"../AnimalCooking/resources/sounds/thunderSound.wav"},
	{Basic, burningFireSound,"../AnimalCooking/resources/sounds/burningFireSound.wav"},
	{Basic, pigeonSound,"../AnimalCooking/resources/sounds/pigeonSound.wav"},
	{Basic, star1Sound,"../AnimalCooking/resources/sounds/1star.wav"},
	{Basic, star2Sound,"../AnimalCooking/resources/sounds/2star.wav"},
	{Basic, star3Sound,"../AnimalCooking/resources/sounds/3star.wav"},

	{Basic, Tecla1,"../AnimalCooking/resources/sounds/tecla1.ogg" },
	{Basic, Tecla2,"../AnimalCooking/resources/sounds/tecla2.ogg" },
	{Basic, Tecla3,"../AnimalCooking/resources/sounds/tecla3.ogg" },
	{Basic, Tecla4,"../AnimalCooking/resources/sounds/tecla4.ogg" },
	{Basic, Tecla5,"../AnimalCooking/resources/sounds/tecla5.ogg" },
	{Basic, Tecla6,"../AnimalCooking/resources/sounds/tecla6.ogg" },

	{AllLevels, End_Win,"../AnimalCooking/resources/sounds/END_WIN.ogg" },
	{AllLevels, End_Lost,"../AnimalCooking/resources/sounds/END_LOST.ogg" }
};

